<a href="https://colab.research.google.com/github/mahdi-014/Customizable-Portfolio/blob/main/Numpy_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.array([1,2,3,4,5])

print(a)

[1 2 3 4 5]


In [2]:
b = np.array([[1,2,3,4],
              [5,6,7,8]
              ])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
c = np.array([[
    [1,2,3,],
     [4,5,6]
    ],
     [
         [3,4,5],
          [9,7,8]
         ]
              ])
print(c)
print("Diamention:",c.ndim)

[[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [9 7 8]]]
Diamention: 3


In [4]:
d = np.array([[1.1, 3.4, 8.4],[1.1, 3.4, 8.4]], dtype=float)
print(d)

[[1.1 3.4 8.4]
 [1.1 3.4 8.4]]


In [5]:
arng = np.arange(1,10,2)
print(arng)

[1 3 5 7 9]


In [6]:
re_shape = np.arange(1,13).reshape(4,3)
print(re_shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
ons = np.ones((3,4))
print(ons)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
zrs = np.zeros((3, 4))
print(zrs)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
linshp = np.linspace(-10,10,10)
print(linshp)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [10]:
idn = np.identity(5)
print(idn)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
n = np.random.randint(0, 10, size=(3,4))
print(n)

[[1 4 9 3]
 [1 7 6 5]
 [2 1 2 2]]


In [12]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [13]:
print(a3.ndim)
print(a3.shape)
print(a3.size)
print(a1.itemsize)
print(a3)
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



3
(2, 2, 2)
8
8
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
int64
float64
int64


In [14]:
print(a3.astype(np.int32))




[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
